### ISSUE TITLE
CLAIM does not seem to be a body part anymore

### ISSUE THREAD

**Issue by NiciusB** [screepers/typed-screeps-arena#11]
Not mentioned in the docs, and it'll error out if used with the following message:
```
SyntaxError: The requested module '/game/constants' does not provide an export named 'CLAIM'
    at (<isolated-vm boundary>)
```

**Comment by thmsndk** [comment]
Hi @NiciusB I assume your issue was resolved since you closed this?

**Comment by NiciusB** [comment]
@thmsndk  I guessed the part exists but not in my arena of choice after seeing people reporting missing variables for that reason in the discord
