### ISSUE TITLE
spawnCreep returns a more general type than is needed

### ISSUE THREAD

**Issue by guyguy2001** [screepers/typed-screeps-arena#12]
spawnCreep is defined as:
```typescript
    /**
     * Start the creep spawning process. The required energy amount can be withdrawn from all spawns and extensions in the room.
     * @returns A creep on success or an errorcode on failure
     */
    spawnCreep(
      body: BodyPartConstant[]
    ): { object?: Creep; error?: ERR_BUSY | ERR_INVALID_ARGS | ERR_NOT_ENOUGH_ENERGY };
```
But according to both the jsdoc here and the documentation, it never returns both object and error.
This means that in reality, `!spawnCreep().error` implies that an object was returned, but the type inference misses that.

I propose one of the following definitions:
```typescript
   spawnCreep(
      body: BodyPartConstant[]
    ): { object: undefined; error: ERR_BUSY | ERR_INVALID_ARGS | ERR_NOT_ENOUGH_ENERGY } |
 { object: Creep; error: undefined };

   spawnCreep(
      body: BodyPartConstant[]
    ): { error: ERR_BUSY | ERR_INVALID_ARGS | ERR_NOT_ENOUGH_ENERGY } | { object: Creep; };
```
I'm pretty sure the second one is correct (when console.logging the result of spawnCreep it always contained only one of object or error), but only the first one lets me do `if (spawnCreep(...).object)` (although I can still do `if ('object' in spawnCreep(...))`)

**Comment by thmsndk** [comment]
Hi @guyguy2001 Thank you for taking the time to report the issue. 

I agree that the following definition sounds more correct if the spawn method in fact contains either one or the other.

```ts
spawnCreep(
      body: BodyPartConstant[]
    ): { error: ERR_BUSY | ERR_INVALID_ARGS | ERR_NOT_ENOUGH_ENERGY } | { object: Creep; };
```    

If you could make a PR to the develop branch and update the tests https://github.com/screepers/typed-screeps-arena/blob/develop/dist/test/screeps-arena-tests.ts and run the test with `npm run test` it would be very much appreciated :)

**Comment by guyguy2001** [comment]
Just to make sure - the section in the Readme about deploying to definitely typed is for when you publish a version, and not for PRs to your repo, right?

**Comment by thmsndk** [comment]
Yes, it just details how we push types to DT, the `screeps-arena-tests.ts` are however run by DT when we actually do make a PR to them.

the PR you should make should be to this repo (typed-screeps-arena) and it should be a PR from the develop branch :)

**Comment by guyguy2001** [comment]
Alright, I got a long weekend thanks to Passover so I can finally have some free time to do PRs :)

Before I go into it, one usability question -
Currently, I check if the spawn succeeded like this:
```ts
      const creep = spawn.spawnCreep([MOVE, CARRY, MOVE, CARRY]).object;
      if (creep) {
         ...
      }
```
But this gives an error with the new declaration.
How would you change the code to work with it?
While I'm all for being as correct as possible, I don't wanna introduce a breaking change which can be a regression in a lot of cases

**Comment by thmsndk** [comment]
I think I personally would do it the same no matter how it's typed

```ts
      const potentiallySpawnedCreepResult= spawn.spawnCreep([MOVE, CARRY, MOVE, CARRY]);
      if (!potentiallySpawnedCreepResult.error) {
         const creep = potentiallySpawnedCreepResult.object
      }
 ```
 
 keep in mind though that the .object that is returned might not actually get spawned, we can cancel the spawn in the next tick, or an extension could be destroyed on the same tick that we request it to spawn.

**Comment by guyguy2001** [comment]
But this gives the same error:
![image](https://user-images.githubusercontent.com/6932278/163482449-7b5bd081-722b-468d-ad6c-5677404df150.png)
Same if I try to destruct it.
This isn't an issue in this typing:
```ts
   spawnCreep(
      body: BodyPartConstant[]
    ): { object: undefined; error: ERR_BUSY | ERR_INVALID_ARGS | ERR_NOT_ENOUGH_ENERGY } |
 { object: Creep; error: undefined };
```

but then the `"error" in result` guard won't work, because it technically isn't correct (although I'm not sure how much that matters)

**Comment by admon84** [comment]
It has been over 2 years since the previous comment, so I wanted to update this thread before closing it out.

Screeps Arena now generates official typings in dist folders to provide code completion (intellisense) for javascript players.

The official types specifies the `spawnCreep` method returning a `SpawnCreepResult`:

https://github.com/screeps/arena-definitions/blob/3f1f33ede4d1bba7cb3553d942e906e8e22e5a39/common/typings/game/prototypes/spawn.d.ts#L7-L13

```js
export interface SpawnCreepResult {
    /** the instance of the {@link Creep} being spawned */
    object?: Creep | undefined;

    /** the error code */
    error?: typeof ERR_NOT_OWNER | typeof ERR_INVALID_ARGS | typeof ERR_NOT_ENOUGH_ENERGY | typeof ERR_BUSY | undefined;
}
```

This matches the return type that we used previously in the `season-alpha` branch.

The type has been updated in the `season-beta` branch to use the `SpawnCreepResult` name.

Here is some example code that demonstrates calling the `spawnCreep` method in Screeps Arena during Season Alpha:

```ts
const mySpawn = getObjectsByPrototype(StructureSpawn).find((spawn) => spawn.my);
const body = [ATTACK, MOVE];
const { object: creep, error } = mySpawn.spawnCreep(body);

if (creep) {
  console.log('Creep spawning:', creep);
}

if (error) {
  console.log('Spawn error:', error);
}
```
