### ISSUE TITLE
structureType does not exist anymore

### ISSUE THREAD

**Issue by lmik** [screepers/typed-screeps-arena#15]
quick note that structures dont have this prop anymore.

**Comment by thmsndk** [comment]
oh, so this one does not exist anymore?
https://github.com/screepers/typed-screeps-arena/blob/0f10bf0633dcce71a6f98cc24ad25f3875045a4f/dist/game/prototypes/structure.d.ts#L35

How are we supposed to determine the type then instanceof?
does that mean all the `STRUCTURE_XXX` constants are removed as well?

**Comment by lmik** [comment]
not entirely sure if the structure constants are gone too, i would assume they are? just quickly threw the issue in so its not forgotten :D 

and yes, instanceof or whatever other way

**Comment by thmsndk** [comment]
seems like STRUCTURE_XXX is gone from the docs, I guess that needs to be removed, it's used extensively in the types currently though so a lot of cleanup is needed

**Comment by lmik** [comment]
closing this as it is fixed in develop
