### ISSUE TITLE
`createConstructionSite` overload that is not in document

### ISSUE THREAD

**Issue by somq14** [screepers/typed-screeps-arena#18]
In the docuemnt, `createConstructionSite` has no overload, but in type defintion do.
I would like to know whether this is mistake or intended.

https://github.com/screepers/typed-screeps-arena/blob/fc27b6d30318a08eb1f76ac4c7197eac52f068db/dist/game/utils.d.ts#L108-L136

**Comment by thmsndk** [comment]
The docs detailed you can use x, y or an object with x, y at least when we made the typings 
I think it is still implemented that way? I'm not at my pc currently, so I can't verify it.

**Comment by somq14** [comment]
I see. I verfied that both works fine.
I'm not sure which should we respect, document or implemetation.

How about `createConstructionSite` in `dist/game/index.d.ts` ?
I tried following code. It doesn't work.
```
console.log(createConstructionSite(52, 52, "tower")); // { error: -10 }
```

**↓ edited ↓** 
I seem that there are three definitions of `createConstructionSite`.

https://github.com/screepers/typed-screeps-arena/blob/fc27b6d30318a08eb1f76ac4c7197eac52f068db/dist/game/utils.d.ts#L108-L136
https://github.com/screepers/typed-screeps-arena/blob/133a3ef7d44e30acf9f66e741d27cc0bd935f589/dist/game/index.d.ts#L52-L59

By the way, the description for `createConstructionSite` in docs is strange. I seem that it is the description for `findClosestByPath`.

**Comment by thmsndk** [comment]
Well, the docs says this.
![image](https://user-images.githubusercontent.com/9084377/163812286-912c45fc-1300-4408-be1f-cf34623b8a18.png)
And I'm pretty sure that structureType was deprecated at some point, it's been removed from Structure at least when we look at https://github.com/screepers/typed-screeps-arena/issues/15

does this work ?
`console.log(createConstructionSite(52, 52, StructureTower)); // { error: -10 }` i'm pretty sure that is the intention of the overload.

i nregards to `game/index.d.ts` a lot of code was exported in the game interface as well, I'm unsure if it still is.

**Comment by somq14** [comment]
>does this work ?
console.log(createConstructionSite(52, 52, StructureTower)); // { error: -10 } i'm pretty sure that is the intention of the overload.

Yes. It works.

code
```typescript
  console.log(createConstructionSite({ x: 50, y: 50 }, StructureTower)); // works !!
  console.log(createConstructionSite(51, 51, StructureTower)); // works !!
  console.log(createConstructionSite(52, 52, "tower")); // not works...  
```

output
```
{
  object: ConstructionSite {
    id: undefined,
    x: undefined,
    y: undefined,
    ticksToDecay: undefined,
    progress: undefined,
    progressTotal: undefined,
    my: undefined,
    structure: StructureTower {}
  }
}
{
  object: ConstructionSite {
    id: undefined,
    x: undefined,
    y: undefined,
    ticksToDecay: undefined,
    progress: undefined,
    progressTotal: undefined,
    my: undefined,
    structure: StructureTower {}
  }
}
{ error: -10 }
```
![image](https://user-images.githubusercontent.com/54357320/163815983-0c72e1e8-61df-46ab-b35c-3977a61fc5db.png)

**Comment by thmsndk** [comment]
Well then the types works as expected imho, perhaps we should report the missing overload on the steam forums :)
as you can see the one you mentioned not working does ping out with an error.
![image](https://user-images.githubusercontent.com/9084377/163891900-db468764-22a3-4fb8-ba8a-4fa2dce1107d.png)

**Comment by thmsndk** [comment]
the x,y overload is deprecated see this message from o4
https://discord.com/channels/860665589738635336/864240860580151366/965756373256245248

**Comment by somq14** [comment]
>as you can see the one you mentioned not working does ping out with an error.

If we import `createConstructionSite` from `"/game"`, it doesn't report error.
![image](https://user-images.githubusercontent.com/54357320/164001557-0aab01d8-a89f-4b7a-923e-54da3835da10.png)

This relates to #15 so I agree to close this issue.
