### ISSUE TITLE
wrong createConstructionSite() definition in dist/game/index.d.ts

### ISSUE THREAD

**Issue by lmik** [screepers/typed-screeps-arena#23]
i _think_ the fix is to just remove the definition, since the file exports the correct definitions via `export * from "game/utils"`

related to #15

**Comment by thmsndk** [comment]
I think that export was removed in one of the PRs I just merged in, 

are you saying this is wrong? and it should be exported from game/utils?
https://github.com/screepers/typed-screeps-arena/blob/b9b3a5f82c78f6aec87ec6e40d1a44d23e536ada/dist/game/index.d.ts#L52-L59

**Comment by thmsndk** [comment]
According to the docs it should exist in `/game/utils`. is it perhaps a leftover that it is exposed in `game` ?
Perhaps we should just remove it completely and direct people to using the one in utils?

![image](https://user-images.githubusercontent.com/9084377/167814810-3be3349d-b374-4734-b3a3-e140df068b3d.png)

**Comment by lmik** [comment]
> I think that export was removed in one of the PRs I just merged in,
> 
> are you saying this is wrong? and it should be exported from game/utils?
> 
> https://github.com/screepers/typed-screeps-arena/blob/b9b3a5f82c78f6aec87ec6e40d1a44d23e536ada/dist/game/index.d.ts#L52-L59

the definition is wrong entirely, structureType isnt a string. so if you import from game you get invalid errors

removing that definition and just exporting game/utils should fix it

**Comment by thmsndk** [comment]
I kinda feel like just removing that definition entirely from game, not exporting it at all there, I think it's a leftover from alpha and the devs intend for it to live in utils? at least based on the docs.
